---
- name: Install python dependencies
  apt: name="{{ item }}" state=installed
  become: true
  become_user: 'root'
  with_items:
    - 'python-psycopg2'

- include: databases.yml
- include: user.yml
