- name: Create a read/write user
  postgresql_user: >
    state=present
    db="{{ item }}"
    name="{{ item }}_openregister"
    priv=CONNECT
    role_attr_flags=NOCREATEROLE,NOCREATEUSER,NOCREATEDB,INHERIT,LOGIN,NOREPLICATION
    password="{{ lookup('pass', '{{ vpc }}/rds/openregister/{{ item }}') }}"
    no_password_changes=yes
    login_host="{{ groups[inventory_group_name][0] }}"
    login_user="{{ master_user }}"
    login_password="{{ master_password }}"
  with_items: "{{ register_groups.keys() }}"
  when: create_db

- name: Set privileges for user
  postgresql_privs:
    state=present
    db="{{ item }}"
    roles="{{ item }}_openregister"
    type=database
    privs=CREATE
    login_host="{{ groups[inventory_group_name][0] }}"
    login_user="{{ master_user }}"
    login_password="{{ master_password }}"
  with_items: "{{ register_groups.keys() }}"
