#cloud-config

users:
  - default

  - name: michaelabenyohai
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBWdzo8bSa/jm95AtgkRmIOMOxXt6sBtA/s6tkQ4R5I+ZM+jK0Gpf+AuIwzlNMIZjNXnH9FeX0Grm+gGK+wRUSbjRMkzoAl3fJhwDII5XY375aiz8VcuLEwW0n4/tGu1qKB3UlB67etxdHBksrgNFEJPA3/EzOizuugVFC396dUIzWEBVFJ6fY/LIlaBnQWkO5lT7+t+PnoBG5dPNslDEYgfp/+p9MxgAX/kzSpEzc1qrtcTwzZHMaO7F5Qix2+QeZ4GTDY3kuDnYbHKRXFHN9lOYoUxHLjXiRNiyqxx5Z+d7QQE76sxidt7d5//amJY6F3KQzXqpJqfbXfJ0ZPFE33BS5SAZx+o/6oE35yays8DjGT98piOGKko0OtCZYM2wiv+d51KMKIU+BFKv9ZxDlMLr/hQulTtjR3BaAWDfLISzaB1N5qqinYXbmEV31z/ymcYGK2LHpV4nIs60ph2CFLzB+nr4eUmf7AbK9IPmYnCnj6JRFwvF7JYsDcNurDcfzkt+dponq2jJnH2SeEjghS1BW+cif8xJtXCdz2i1P6i/ISt19Enwck6iHJ5FjT6zamupp2Lpp+1sFBKoKX60ILGeUQMAzDjCV1mCUhzh8mu9cmf7LGahht+PCX7zBB4NTt5fOYo7uSW1AFB0sPaZwMlFmeO9G7e/5Feq8sXqBvQ== michaelabenyohai
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

  - name: endamccormack
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUXIDMVdw5yLzztOiIw8ZfPP1QO8+Auh+TK2+hpe0OAkUt7ifc+hoCeN/eJpvANTR019AqWEQ/OBoUyXE/lDbctvjkqxXTMD8iaQRtC2L3a09rSenh8qTgFWsLrd3sFnXPbYmQL1kUqnwDXLaw882Q+jPZXCEzowN8NNcSOB3ZrHvg50B4S6TBdVkwDx1yb9EnqaDRnoBuUPScnXrfB2/ZmWVEiz4m1LWj0yQcuw6YdHljl3l3GrRo78re20rwHXOkHcE7tkSSRankk+Z+aI5qWW/uNoXT0LbiA64QcQDfwrS45wHtUSbZp6pzZ4St7XwJy/HqRqn0IoA0kRDp5wmmjnNqoFBDmjrnLUVxC2iYOz53RlF8CGIMApvYWi1c+yTh3GwPHyYqCWP389KSLduMKIgyiGon11Qgco/75VJTfFHMzwf8sFE0PRe7w8p8irxB4/Khjg6BUdwyFxHbbsVcKiI25Zv3smJgFj2F0lG1yHwvh3cy4JC59MDrkRF4ZWAaakxTcpJOaDHyx8GOVKSBMgIyfDiGrBMx7iNQ6tZxYs8D420w2rA+L2FT+MUyPgaAmgNvEcZ/uxcTaVJnbwn+YfV7KfX3TvRfwLnLCB72qTtG3ZDlF7EmmQFDNy6nI8q+fty9s0cF15b9jnogzE+pPWi8iZI4KltGZaW1BdL03w== enda.mccormack@digital.cabinet-office.gov.uk
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

  - name: karlbaker
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCo6AI0U+VFs2dkrwNDMKcU7j5lhSPFDuboQrsGyC1tv8aUBlCSfVDaPRPT20lYANN7tFgQD9mKXaMlUd9bCJJFs7L3CbE+/kSQCE85rfPFDaTMb3/WzYzwMjDD05pRtvdBwmkS6o8IFA4Yyd29qahYhnrO3jexBIZnNdM4nWZCac+nX/8bWckPOGWIR7fTNWoS8C8tioiUDqa/ZflzGqA0NKv7M0I1kwKqHt25FHaqZxnGmnKEC9QIUGbS4cC1cJQ2AO3NqJGPWhb39QrZwvv+Juh9rU3vuohDfx7Xm1Lh8NMVf3+c1vNTcK+DvaGGLZJ20JUBXlRRFFviLo9eaaf5fHIn5bM9aKFwxoPZtlj73FQpv04bUJf/LlbnGgLeW+B6Pl2w2qFp3u5p5NtvPEnLLPm4ljiPsJwl6vdmZy/xLc8/Ze0xyOeMaENm9MFK8BykgBqXqmEsSntvryP2fp1LgwDOt9ufLpF+yLq6hXl/JKYDJZiCTUjpwSbO/GRbsf2PCjzcwLxKIru3QtR9IZmiopeYRbDvH6Zofs/4M4mQVlBv15CKthVSTwwvcb9vOQyRa2uRW6FkY//g04+2yXpU742Cuh0CgNUd1fJ/vO3kCO0Fup/m3M0B7Vsr4NE5/0XdZSXOd5sF9oB4uVh9vE7apD0+hGbeQHzXz5cRNn52KQ== karl.alec.baker@gmail.com
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

  - name: samcrang
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDHtO59/mISjM3EzlKPn3A38IdiJfhGekrR+RLMc9/+AoTFGjmIZRKNDHRHhD4q5GJVEmB9QXxSt0sv4b5ufr3PEJR0DEZ9fKL038nVZyV6OEbSzolif04iFGPHycmRU4zErm5vJyN/FJTxptwkPWlgpyBx4ctFICqtBGAivRqCg3l59icEtOTo94Paz8cFidI1YTolj6hG2KbrZWGG4DGZ6O9CjcSkyYk3BJLxPGLPS8rW/zy1Fp3qXA4q1CCpYi4FQ7o1L8l8OOkBp0Uwq332ijO0pezOt4CyGqMdmITKQpQS2kE1nJpMi9A+Flu/T9ZrgrRgm8NVARlSYUc0QmnQObzMtwmmLhY3K6nesToQraikhnMqpHnmYhtuHH3JYGC7zeLR8RHZqqb7LCLZf4jmNDQbAtCHVgo5sQxw84dZKNKqWIbD1Jbkd9vOoNUM2I/TJQDtwVjzljlWdzIq68q3IKZBJS1x/n35vlyyNaEHSs3TdM0yYnKDukFqWbflzwm7Zl+X1NsuRSAdmShc4jzDGreUm9fRUTY+vtTjbIyo+Sv4nmVmWEjV9NH/DL93m9yKn10ZOOgEp/OFGE/nvapV2v+jz96plC0GCKUgJ/KxFqbxfW6T596bODsqr66553Q+ZjT/yBHzN7tO3T4SXRdn/qQvPkP+yAg76wtPwiFspQ== sam.crang@digital.cabinet-office.gov.uk GPG:B91590AEA3A6B81BCAE99ADC1F07315057BC3A55
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

  - name: ggoldberg
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBZpQYtgsCk+W1m9Sq+1+MTiRfvrwXOIQPCb5sQ2oEgQTrGCrB5BrTLR8ubbhn/acETG9gHL0hAQgZR40GHgPVwefQJwiQ8I44QAldtcOKCd0Ivy5ZKQYaPbQPXrUHS6xCLvxicfvLfv1jNOQCaAJ1+cXePobvZ4t2meh2SpbXZI9ccLIn9SUvlzeF0YI7bxJ5M/WZGGuuQWzfVX4ylRdWC2rsqU4G7z61f56pb9hOLb/y2v8X1iU3ZY/A1HuM4cxRVH5zNcakA2G19CR0pptuHVlokt4sAiQWvJwHrw27xIdv62QzE5SmYSLAFN70+2jER7wiF/GZ/RTPrWDflZ2V gidsg@github.com
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash

packages:
  - awscli
  - docker.io
  - python
  - ruby
  - update-notifier-common # required for automatic reboots
  - unattended-upgrades

package_upgrade: true
package_reboot_if_required: true

write_files:
- path: /usr/local/bin/setup-cdagent.sh
  permissions: '0755'
  content: |
    #!/bin/bash

    aws s3 cp s3://aws-codedeploy-eu-west-1/latest/install /tmp/install --region eu-west-1
    chmod +x /tmp/install
    /tmp/install auto
- path: /etc/apt/apt.conf.d/50unattended-upgrades
  permissions: '0644'
  content: |
    // Automatically upgrade packages from these (origin:archive) pairs
    Unattended-Upgrade::Allowed-Origins {
            "${distro_id}:${distro_codename}";
            "${distro_id}:${distro_codename}-security";
    //      "${distro_id}:${distro_codename}-updates";
    //      "${distro_id}:${distro_codename}-proposed";
    //      "${distro_id}:${distro_codename}-backports";
    };

    // List of packages to not update (regexp are supported)
    Unattended-Upgrade::Package-Blacklist {
    //      "vim";
    //      "libc6";
    //      "libc6-dev";
    //      "libc6-i686";
    };
    
    Unattended-Upgrade::Automatic-Reboot "true";

runcmd:
  - [ systemctl, enable, docker.service ]
  - [ systemctl, start, docker.service ]
  - [ /usr/local/bin/setup-cdagent.sh ]
