#cloud-config

users:
  - default
  - name: philandstuff
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpD0Wc0pfD5NrV0D7alwOZDIqC9id+RroF2BQ59wLqxvF4wvlgtab0VHiIylSeN4K2bK5ikugy6/rwhWWdoQ3raMXIgOWP6ukSh/OLUioxCeop04IlF4JgUo3uNoInkUegnLw42sg/cKX+pbv/1Rc4GEO6J0Wy6YylyeieAWiy2rwgO/nr/49Tyiw1C66embmglhv7OaZEthpKyM3u6rlJeeU0H2K/bsc9yU/Utpek0hx/nih8qlVEPG7/3welWUNb/LwFC4EpJKiU72mRcjWGh9l5MjCJ2SR/wimY1AHQ4YES3VeAQvcaTKMCnaBET/RhnashxMr0f3V7IDkg56tZ cardno:000603815000
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: omsharma
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC7u+dU4GpcG73nZD4BJGuq8s9roUGSrSKE8dJ/b224t8sUFtr+G8Aa6i90p+qwAnoH/x9ZtUW2CV/qjHGVT1FprHvFHIjPJ7lvFiGm9TQIFQYz2ps7nUDHybWDXCxN2quF2VLRyvSuhEwXLyqL+OdpYl+7VmchfL9jgumkcPRjh2q+7h3l3Bio0tvy6m40QKjbqRXG0bdOAaQMApkWLm5J438WxMum1sfVgcpDBopeK2WYF5eFmnLefzynlpxrRagRSuTqCJ+uPpQJSPhBYjyXu4UtkUr9xCJJx+jSrvgkeyXA4ZVZDaW5FVnr6CdlDJwCx6Y3gB2CIGqA+B/HIsmR OmSharma
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: andrewg
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYe5kyPAPj8pLNAwa/VXzZP2I7/PsiErQ0dabRt3teHMa8bkuEASUc0KsSb3cTNLnAhoJ+KHBPXCGw7d7fgRtjgaGihfpNTPq10swOMqFSnW4NrOpqcINgoETNfdrRbvl3hxPfj8ZRFMFjs+yM74kG0r/aBjb5u8Q6b3IAx/jyouD28kWHAXZBeM6dEevsC5bpGLpcdrWUKGAoH7WM8FQvCkwkBFYIdD/LPu6sNUMcuNvyUtADCV1GpyZcFGp/mFyLxuZ8/lex9GkEh6PhOxNFeOOrQ57AlT3ShpUSE4MN3oQlQeSj6nGXrxsWKsxZ9wrFKxlNVoyB/YxkzrS3DcY46rrdpFI9MM+D/dxG7+1QWaEBYje5A4c9eABQTU4xTTJQJkAKRASLC1ZCd03JY5ialM7vlf7Q8fEh349Ztfj+HXvl+KwHNilEy9728etXoZ5lYpjcmq/ZgAfwGj7r1dMReEUm+JJZ4dQLrzGyXTRFRh+LAnc1zFhWV0BP0RGEFoyPy+PWcXh9BblcUbncfAbYKC9ZtBPK3HBE1uA98Z40egjQ6Mb/KNgq+e4SF4i9SIamLQqbXdkYE3OBoaxZ0Ysox+Xh0E1EfRKGnqqum5mBCRhZyo2xT5XjZlfMFRwkGuJgAbwiyM9AtYgKHJuSLULW5bqXEfyqM8r5zLfwQ8nsnQ== andrewg
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: slawekm
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCgjBGOBq7B1nRKO4TlJlNk/dyS2IpvrMaRw8+SAhdmgVQo8jqZkwFhS5gjnqT7IOAlPqptlHrhW28cr5HrvSY7LN9lv5mmzjFt4nHg2Fdro8v13mHToAp0ySWj1G7yf+1mviXj2kF3EIz6ScZLn2J/W3Glg9vYz/sHd9bHgPBpARo0MKmCoZHL0gEsWEwqEDYhY2AOLbPUN1qwG3Ofn4kRbGoLumz1vBnRzQeF/V9th+b6dTx/V6H8+d3An5AoXmYmbHdb4LBWtkqP577st8zl0JVOYwAoSmFxaTS2/fFVcq0v57RwF82igkg6aLQPIIPcyOzsSJTh5jl/uHYP7WMgIljksHFzTVF7YQS0REIbcP0rtIrEyf4lL3smEFdoUCKeHIcWuIS7FPlduKWV4Z/OZfzqgVDbDuPTOfjr4hXbYKXqGYx75SVGtwCE8BmeaIkUEOW/LsbPEueIQu35uc5tiQfFrXdxEQDw/xRJWMuz7REwQjZ1CthBRtrg5wu8r2OXtTUl2gvUPV3HQ8/T80ENnwLK/kVWkbM1bBZn8QlcF3JbMMJU1Y4EjTWgTH1gGPy7a9uvdE8F4suhVcrSTiCJu6WqaegsnJtsAjMGmMONtBRhVkipA9PGWCoCumN1grO8xBHxNr0oENeAX6C218dzVyY+tER8V/prV0nTEUZ1lw== slawekm
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: andrewg
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDYe5kyPAPj8pLNAwa/VXzZP2I7/PsiErQ0dabRt3teHMa8bkuEASUc0KsSb3cTNLnAhoJ+KHBPXCGw7d7fgRtjgaGihfpNTPq10swOMqFSnW4NrOpqcINgoETNfdrRbvl3hxPfj8ZRFMFjs+yM74kG0r/aBjb5u8Q6b3IAx/jyouD28kWHAXZBeM6dEevsC5bpGLpcdrWUKGAoH7WM8FQvCkwkBFYIdD/LPu6sNUMcuNvyUtADCV1GpyZcFGp/mFyLxuZ8/lex9GkEh6PhOxNFeOOrQ57AlT3ShpUSE4MN3oQlQeSj6nGXrxsWKsxZ9wrFKxlNVoyB/YxkzrS3DcY46rrdpFI9MM+D/dxG7+1QWaEBYje5A4c9eABQTU4xTTJQJkAKRASLC1ZCd03JY5ialM7vlf7Q8fEh349Ztfj+HXvl+KwHNilEy9728etXoZ5lYpjcmq/ZgAfwGj7r1dMReEUm+JJZ4dQLrzGyXTRFRh+LAnc1zFhWV0BP0RGEFoyPy+PWcXh9BblcUbncfAbYKC9ZtBPK3HBE1uA98Z40egjQ6Mb/KNgq+e4SF4i9SIamLQqbXdkYE3OBoaxZ0Ysox+Xh0E1EfRKGnqqum5mBCRhZyo2xT5XjZlfMFRwkGuJgAbwiyM9AtYgKHJuSLULW5bqXEfyqM8r5zLfwQ8nsnQ== andrewg
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
  - docker

package_upgrade: true

write_files:
- path: /usr/local/bin/setup-cdagent.sh
  permissions: '0755'
  content: |
    #!/bin/bash

    aws s3 cp s3://aws-codedeploy-eu-west-1/latest/install /tmp/install --region eu-west-1
    chmod +x /tmp/install
    /tmp/install auto

runcmd:
  - [ service, docker, start ]
  - [ docker, pull, jstepien/openjdk8 ] # make this available for app deployments
  - [ /usr/local/bin/setup-cdagent.sh ]
