#cloud-config

users:
  - default
  - name: philandstuff
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsYvhPkvKma2RwWVwUNJ2fcoNjlObibUka0fl5WcctTokz8RISDkOAPjz+L0QmGsq/Dhgn/mbspKFyNKvQsujeooEpaO+cjYPXoUF1NTxhbUrMEu2uE+CPoj4zPbAZ9A6LdxkL13F3gJwZi9k8K9+6AnJeB4IrCLS5KHRiL+tBZMLPvKnn54M6PCfkWJH6zVO92plFTpRX1W4GanUwYGTemFX0qUwFgZu9OJvGiR+ZQKJMQ2Y3O+IMHv1KusfBrO+Q4iWn+A5VcJRoxml3lr0fYlbaetCpszkaY5HbQsLPDGtvsN1jXj2ghVe2ZbK8SKe13g+LSqYxmIX5qCAoEi+J philip.potter@digital.cabinet-office.gov.uk
    sudo: ALL=(ALL) NOPASSWD:ALL
  - name: omsharma
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDcntQbymoWmb4l2xztDMu+6KAa9+ykyarqxFhkejGXNy0fgUlm0P8Td7vI5/AU4YAGiOgLjq38B/OADhv40x0L66Zi5TkHAL+XWgQ+yKPjsc170WCJy6nv5gInPhPZ794H6v0JT+9i1/f7Cs5PiVrWfIF9oj4ZtUpDUjSPzsk86b07n+384thSO6gB5fugCkIYan7Uyk05v8yAoHpkelyNTzLdRWtIqOQvtt1vQnC6ZBV7M6JAQQAzXnJnhTaPjY6Dy7a3co5HQonhjsDSo151dcfngyEmdbs4yRB4ZHBsyno26bSNKzKv2ltKrVr+/NKgtbyIDdUXaopuT9drKvM3 foromsharma@gmail.com
    sudo: ALL=(ALL) NOPASSWD:ALL

packages:
  - docker

package_upgrade: true

write_files:
- path: /etc/docker-compose.yml.template
  permissions: '0600'
  content: |
    zookeeper:
      name: zookeeper
      image: wurstmeister/zookeeper:latest
      ports:
        - "2181:2181"
        - "2888:2888"
        - "3888:3888"

    kafka:
      restart: always
      name: kafka
      image: wurstmeister/kafka
      ports:
        - "9092:9092"
      links:
        - zookeeper
      environment:
        BROKER_ID: 1
        PORT: 9092
        KAFKA_ADVERTISED_HOST_NAME: __KAFKA_ADVERTISED_HOST_NAME__
        KAFKA_ZOOKEEPER_CONNECT: zookeeper
        KAFKA_CREATE_TOPICS: "register:1:1"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

    postgres:
      restart: always
      name: postgres
      image: postgres:9.4
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: '%PGPASSWD%'

- path: /usr/local/bin/start-docker
  permissions: '0755'
  content: |
    #!/bin/bash

    umask 0077
    
    export cip="$(ifconfig |egrep -C1 'eth0[ \t]' | tail -1 | sed 's/[ \t]\{1,\}/|/g'|cut -d\| -f3 | cut -d\: -f2)"
    cat /etc/docker-compose.yml.template | \
      sed -e 's/__KAFKA_ADVERTISED_HOST_NAME__/'$cip'/g' \
      > /etc/docker-compose.yml

    /usr/local/bin/docker-compose -f /etc/docker-compose.yml up -d

- path: /usr/local/bin/setup-cdagent.sh
  permissions: '0755'
  content: |
    #!/bin/bash
     
    aws s3 cp s3://aws-codedeploy-eu-west-1/latest/install /tmp/install --region eu-west-1
    chmod +x /tmp/install
    /tmp/install auto

runcmd:
  - [ service, docker, start ]
  - [ pip, install, docker-compose==1.3.3 ] # docker-compose 1.4.0 requires docker >=1.7.1
  - [ docker, pull, jstepien/openjdk8 ] # make this available for app deployments
  - [ /usr/local/bin/start-docker ]
  - [ /usr/local/bin/setup-cdagent.sh ]
