---
- name: Validate we run with the correct Ansible version
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    expected_version: '2.2.1.0'
  tasks:
    - assert:
        that:
          - ansible_version is defined
          - ansible_version.full|version_compare(expected_version, '=')
        msg: This playbook must be run with ansible {{ expected_version }}
      run_once:   True
