#cloud-config

users:
  - default

  - name: chrisduraj
    group: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCVVhDnVJvuYocL64Vu6Pr+AJRRrp15UciKpbSsvplhw5l5oc1yvB/+a4oi6AGZZUu66Gk7FGS2f3ESQBP5yPPkKJS+SHACjTqNpGD9OwMb4hRdAiK14gEn5CJDeGF/6gnG31vWeh9ZHlzU0TEfIICIpZ1ojYJu8YM+cuhuuXHIknK9iDngGDIlbhbqA57hts5IsqdktwZgDlJe1h2F/QbU1/+xadjrR7v+tCDhUlw52zHvgeW5hCqnG24Px7zea5eYkShmMjVKtqpJqZWfKaxPaYnJRpbtKpT8L3IyIWdagemxiPsgyG5LglrMdlxRDl9CHUtyBDeMLm23wkWrWQn0LKe07qhUltWvg4UXI8x5j7NzKATNIPB7BTbeQyMbgiGHEWloy9dkJBuNQKSUFQyolFG6lj9z+ea6w80q7f9Of9ylXtaNGWHuP253fSUwU+5mjYaSuQcI7rqk0rU2I6QT1NEXmtM3SPDkNDUfDDrN6d2HYpOHCbzqS0ygH2uVYrfPPG3Unef35MVSIA0KAxpXhoWTNg/pZ2hh+y3YbFKclVqXFFy3R8ka39LKTn+NYWW1Dsb/81EjeTxcfRLKzUTED+Wu5n/Trb0q0YYJld1Hyye9UL0fJ91oEm79AN0+TQXNMemxyIwuqYSruF787eLHcb7mqs9ACiEqkIytCGMXaQ== christopherduraj@gmail.com
    sudo: ALL=(ALL) NOPASSWD:ALL

  - name: philandstuff
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpD0Wc0pfD5NrV0D7alwOZDIqC9id+RroF2BQ59wLqxvF4wvlgtab0VHiIylSeN4K2bK5ikugy6/rwhWWdoQ3raMXIgOWP6ukSh/OLUioxCeop04IlF4JgUo3uNoInkUegnLw42sg/cKX+pbv/1Rc4GEO6J0Wy6YylyeieAWiy2rwgO/nr/49Tyiw1C66embmglhv7OaZEthpKyM3u6rlJeeU0H2K/bsc9yU/Utpek0hx/nih8qlVEPG7/3welWUNb/LwFC4EpJKiU72mRcjWGh9l5MjCJ2SR/wimY1AHQ4YES3VeAQvcaTKMCnaBET/RhnashxMr0f3V7IDkg56tZ cardno:000603815000
    sudo: ALL=(ALL) NOPASSWD:ALL

  - name: michaelabenyohai
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDBWdzo8bSa/jm95AtgkRmIOMOxXt6sBtA/s6tkQ4R5I+ZM+jK0Gpf+AuIwzlNMIZjNXnH9FeX0Grm+gGK+wRUSbjRMkzoAl3fJhwDII5XY375aiz8VcuLEwW0n4/tGu1qKB3UlB67etxdHBksrgNFEJPA3/EzOizuugVFC396dUIzWEBVFJ6fY/LIlaBnQWkO5lT7+t+PnoBG5dPNslDEYgfp/+p9MxgAX/kzSpEzc1qrtcTwzZHMaO7F5Qix2+QeZ4GTDY3kuDnYbHKRXFHN9lOYoUxHLjXiRNiyqxx5Z+d7QQE76sxidt7d5//amJY6F3KQzXqpJqfbXfJ0ZPFE33BS5SAZx+o/6oE35yays8DjGT98piOGKko0OtCZYM2wiv+d51KMKIU+BFKv9ZxDlMLr/hQulTtjR3BaAWDfLISzaB1N5qqinYXbmEV31z/ymcYGK2LHpV4nIs60ph2CFLzB+nr4eUmf7AbK9IPmYnCnj6JRFwvF7JYsDcNurDcfzkt+dponq2jJnH2SeEjghS1BW+cif8xJtXCdz2i1P6i/ISt19Enwck6iHJ5FjT6zamupp2Lpp+1sFBKoKX60ILGeUQMAzDjCV1mCUhzh8mu9cmf7LGahht+PCX7zBB4NTt5fOYo7uSW1AFB0sPaZwMlFmeO9G7e/5Feq8sXqBvQ== michaelabenyohai
    sudo: ALL=(ALL) NOPASSWD:ALL


packages:
  - aws-cli
  - docker
  - ruby

package_upgrade: true

write_files:
- path: /usr/local/bin/setup-cdagent.sh
  permissions: '0755'
  content: |
    #!/bin/bash

    aws s3 cp s3://aws-codedeploy-eu-west-1/latest/install /tmp/install --region eu-west-1
    chmod +x /tmp/install
    /tmp/install auto

runcmd:
  - [ service, docker, start ]
  - [ docker, pull, jstepien/openjdk8 ] # make this available for app deployments
  - [ /usr/local/bin/setup-cdagent.sh ]
