#cloud-config

users:
  - default

  - name: chrisduraj
    group: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCVVhDnVJvuYocL64Vu6Pr+AJRRrp15UciKpbSsvplhw5l5oc1yvB/+a4oi6AGZZUu66Gk7FGS2f3ESQBP5yPPkKJS+SHACjTqNpGD9OwMb4hRdAiK14gEn5CJDeGF/6gnG31vWeh9ZHlzU0TEfIICIpZ1ojYJu8YM+cuhuuXHIknK9iDngGDIlbhbqA57hts5IsqdktwZgDlJe1h2F/QbU1/+xadjrR7v+tCDhUlw52zHvgeW5hCqnG24Px7zea5eYkShmMjVKtqpJqZWfKaxPaYnJRpbtKpT8L3IyIWdagemxiPsgyG5LglrMdlxRDl9CHUtyBDeMLm23wkWrWQn0LKe07qhUltWvg4UXI8x5j7NzKATNIPB7BTbeQyMbgiGHEWloy9dkJBuNQKSUFQyolFG6lj9z+ea6w80q7f9Of9ylXtaNGWHuP253fSUwU+5mjYaSuQcI7rqk0rU2I6QT1NEXmtM3SPDkNDUfDDrN6d2HYpOHCbzqS0ygH2uVYrfPPG3Unef35MVSIA0KAxpXhoWTNg/pZ2hh+y3YbFKclVqXFFy3R8ka39LKTn+NYWW1Dsb/81EjeTxcfRLKzUTED+Wu5n/Trb0q0YYJld1Hyye9UL0fJ91oEm79AN0+TQXNMemxyIwuqYSruF787eLHcb7mqs9ACiEqkIytCGMXaQ== christopherduraj@gmail.com
    sudo: ALL=(ALL) NOPASSWD:ALL

  - name: philandstuff
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpD0Wc0pfD5NrV0D7alwOZDIqC9id+RroF2BQ59wLqxvF4wvlgtab0VHiIylSeN4K2bK5ikugy6/rwhWWdoQ3raMXIgOWP6ukSh/OLUioxCeop04IlF4JgUo3uNoInkUegnLw42sg/cKX+pbv/1Rc4GEO6J0Wy6YylyeieAWiy2rwgO/nr/49Tyiw1C66embmglhv7OaZEthpKyM3u6rlJeeU0H2K/bsc9yU/Utpek0hx/nih8qlVEPG7/3welWUNb/LwFC4EpJKiU72mRcjWGh9l5MjCJ2SR/wimY1AHQ4YES3VeAQvcaTKMCnaBET/RhnashxMr0f3V7IDkg56tZ cardno:000603815000
    sudo: ALL=(ALL) NOPASSWD:ALL

  - name: michaelab
    groups: users
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC0TIzHlEIGZPLhrU1ZC1H5t+Jmh/1ZLwge0dy2alayWAqGuID6KuMW/xplwKhZiZPh7p2tnFurZlknMLLZ+O3BK3DPt3i+PKlmkf91rqJv+81dTQD+s915ay/qe9luaCgNTvdPz7tmvdJkGJglLHJtpR8WFPDvudqF4WXitG1i2RdRfaFpws3Ab4LV5G5pg0FR50hJrNOjO2LtwejxEQvuseO+stTWzft4f21UsPQPNA85OWzG+xrkYnAAWSdnRJnpO+LJ+Ld4FSkidOwMuXyNehANNTJAWS9qqyOgNqH3A2gEGVC7zJIh5gKPF8svYgw2N+U81/I2400ES1Uu9Clb2yZ5QdBEJMIbxNiaNQ5NHnuifONpuV4dSl7UPp8MDkKfEGfixdaPpa/agYLN8JnCeLlVj62xj61Qpzjzk/aUizD6KoUoRV9YT5Ob6YVJjbsI+/tRiRT0/ca8StZvYsymbI+bHEuc7CqmMPo7L1CMo/0YIBfpRCL+dkPEMByqvWNzdsMhiIH8s/rwDVx9CUZKpcDcVmmWHBXLLoRlMu66d2GVYjXdJmdnGiA/A7V7kexABlUo2LcmY58k+kd1uQtFBqVHkI2Yq0TS0wqb07H/8U9oP5SUOEQlO18htSqvZqmjgJiScbrftDCl5Q9rnBAG7S4iTnuaKRgEhbTwrCxAqw== michaela.broschomb@digital.cabinet-office.gov.uk
    sudo: ALL=(ALL) NOPASSWD:ALL


packages:
  - docker

package_upgrade: true

write_files:
- path: /usr/local/bin/setup-cdagent.sh
  permissions: '0755'
  content: |
    #!/bin/bash

    aws s3 cp s3://aws-codedeploy-eu-west-1/latest/install /tmp/install --region eu-west-1
    chmod +x /tmp/install
    /tmp/install auto

runcmd:
  - [ service, docker, start ]
  - [ docker, pull, jstepien/openjdk8 ] # make this available for app deployments
  - [ /usr/local/bin/setup-cdagent.sh ]
