- name: Ensure target directory exists
  command: mktemp -d
  register: tempdir

- set_fact:
    workdir: "{{ tempdir.stdout }}"

- name: Upload data files
  synchronize: src="{{ src_data }}" dest="{{ workdir }}/" set_remote_user={{ set_remote_user }}
  delegate_to: 127.0.0.1
