- set_fact:
    id: "{{ hostvars[inventory_hostname]['register'] }}"

- set_fact:
    src_data: "{{ sources[id]['src_data'] }}"
    src_type: "{{ sources[id]['src_type'] }}"
    target: "{{ sources[id]['target'] | default(omit) }}"
