---
- name: Create databases
  hosts:
    - 'tag_DeploymentGroup_{{ vpc | normalize_ec2_tags }}_openregister_app[0]'

  environment:
    PASSWORD_STORE_DIR: "{{ pass_store_location | expanduser }}"

  vars:
    master_user: 'postgres'

  roles:
    - { role: database,
        inventory_group_name: '{{ vpc }}-openregister-db',
        master_password: "{{ lookup('pass', '{{ vpc }}/rds/openregister/master') }}"
      }

