---
- name: Create databases
  hosts:
    - '&tag_Environment_{{ vpc | normalize_ec2_tags }}'
    - '&tag_Register_territory' # FIXME
    - '&tag_Role_openregister_app' # FIXME

  environment:
    PASSWORD_STORE_DIR: "{{ pass_store_location | expanduser }}"

  vars:
    master_user: 'postgres'

  roles:
    - { role: database,
        inventory_group_name: '{{ vpc }}-openregister-db',
        read_user: 'openregister',
        write_user: 'openregister',
        master_password: "{{ lookup('pass', '{{ vpc }}/rds/openregister/master') }}"
      }

