---
- include: includes/check_ansible_version.yml

- name: Generate environment passwords
  hosts: localhost
  connection: local
  environment:
    PASSWORD_STORE_DIR: "{{ pass_store_location | expanduser }}"

  vars:
    password_length: 10

  tasks:
    - stat: path="group_vars/tag_Environment_{{ vpc }}"
      register: overrides

    - include_vars: "group_vars/tag_Environment_{{ vpc }}"
      when: overrides.stat.exists

    - name: Generate application passwords
      command: "pass generate --no-symbols {{ vpc }}/app/mint/{{ item }} {{ password_length }}"
      args:
        creates: "{{ pass_store_location | expanduser }}/{{ vpc }}/app/mint/{{ item }}.gpg"
      with_flattened:
        - "{{ register_groups.values() }}"

    - name: Generate RDS passwords
      command: "pass generate --no-symbols {{ vpc }}/rds/openregister/{{ item }} {{ password_length }}"
      args:
        creates: "{{ pass_store_location | expanduser }}/{{ vpc }}/rds/openregister/{{ item }}.gpg"
      with_flattened:
        - "{{ register_groups.values() | union(['master']) }}"
