---
- name: Generate environment passwords
  hosts: localhost
  connection: local
  environment:
    PASSWORD_STORE_DIR: "{{ pass_store_location | expanduser }}"

  vars:
    password_length: 10
    app_services:
      - mint

  tasks:
    - stat: path="group_vars/tag_Environment_{{ vpc }}"
      register: overrides

    - include_vars: "group_vars/tag_Environment_{{ vpc }}"
      when: overrides.stat.exists

    - name: Generate application passwords
      command: "pass generate --no-symbols {{ vpc }}/app/{{ item.1 }}/{{ item.0 }} {{ password_length }}"
      args:
        creates: "{{ pass_store_location | expanduser }}/{{ vpc }}/app/{{ item.1 }}/{{ item.0 }}.gpg"
      with_nested:
        - "{{ registers }}"
        - "{{ app_services }}"

    - name: Generate RDS passwords
      command: "pass generate --no-symbols {{ vpc }}/rds/openregister/{{ item }} {{ password_length }}"
      args:
        creates: "{{ pass_store_location | expanduser }}/{{ vpc }}/rds/openregister/{{ item }}.gpg"
      with_items:
        - "{{ registers | union(['master']) }}"
