---
- include: includes/check_ansible_version.yml

- name: Validate input
  hosts: localhost
  vars:
    registers: !!null
  tasks:
    - fail: msg="Variable registers must be specified."
      when: registers is none
      always_run: yes

- name: Compute mint hosts
  hosts: localhost
  vars:
    vpc_tag: 'tag_Environment_{{ vpc }}'
  tasks:
    - name: include matching hosts
      add_host: name="{{ item }}-1.{{ vpc }}.openregister" group="hosts_to_mint" register="{{ item }}"
      with_items: "{{ registers }}"
      always_run: yes

- name: Load data
  hosts: "hosts_to_mint"
  vars:
    set_remote_user: "{{ use_local_username|default(True)|bool }}"
  vars_files:
    - 'roles/service_data/vars/data-sources.yml'
  roles:
    - service_data
