---
- name: Load street-classification data
  hosts:
    - '&tag_Environment_{{ vpc | normalize_ec2_tags }}'
    - '&tag_Role_mint_app'
    - '&tag_Register_street_classification'
  tags:
    - street-classification
    - street_classification

  roles:
    - { role: service_data,
      id: 'street-classification',
      src_data: '../../address-data/data/street-classification',
    }

- name: Load street-surface data
  hosts:
    - '&tag_Environment_{{ vpc | normalize_ec2_tags }}'
    - '&tag_Role_mint_app'
    - '&tag_Register_street_surface'
  tags:
    - street-surface
    - street_surface

  roles:
    - { role: service_data,
      id: 'street-surface',
      src_data: '../../address-data/data/street-surface',
    }
