---
- name: Validate input
  hosts: localhost
  vars:
    registers: !!null
  tasks:
    - fail: msg="Variable registers must be specified."
      when: registers is none
      always_run: yes

- name: Load data
  hosts: "{{ registers }}-1.{{ vpc }}.openregister"
  vars:
    set_remote_user: "{{ use_local_username|default(True)|bool }}"
  vars_files:
    - 'roles/service_data/vars/data-sources.yml'
  roles:
    - service_data
