---
- include: includes/check_ansible_version.yml

- name: Ping openregister
  hosts:
    - '&tag_Environment_{{ vpc | normalize_ec2_tags }}'
    - '&tag_Role_openregister_app'


  tasks:
    - ping:
