---
- name: Ping presentation
  hosts:
    - '&tag_Environment_{{ vpc | normalize_ec2_tags }}'
    - '&tag_Role_presentation_app'

  tasks:
    - ping:

- name: Ping openregister
  hosts:
    - '&tag_Environment_{{ vpc | normalize_ec2_tags }}'
    - '&tag_Role_openregister_app'


  tasks:
    - ping:
