---
- include: includes/check_ansible_version.yml

- name: Remove users
  become: yes
  hosts:
    - '&tag_Environment_{{ vpc | normalize_ec2_tags }}'
  vars:
    users:
      - andrewg
      - omsharma
      - slawekm
  tasks:
    - name: Purge user
      user: name="{{ item }}" state=absent
      with_items: "{{ users }}"

    - name: Remove user directory
      file: path="/home/{{ item }}" state=absent force=yes
      with_items: "{{ users }}"
