- name: Upgrade Amazon Linux instances
  become: yes
  hosts:
    - 'tag_Environment_{{ vpc | normalize_ec2_tags }}'
  tasks:
    - name: yum update
      yum: name='*' update_cache=yes state=latest
      when: ansible_distribution == 'Amazon'
      register: yum_update

    - name: result
      debug: msg='{{ yum_update.results }}'
