---
- name: Upload register configs
  hosts: localhost
  connection: local
  environment:
    PASSWORD_STORE_DIR: "{{ pass_store_location | expanduser }}"

  vars:
    sync: true
    services:
      mint: 'mint-config.yaml'
      presentation: 'config.yaml'
      openregister: 'config.yaml'

    rds_mint_instance_name: "{{ vpc }}-mint-db"
    rds_presentation_instance_name: "{{ vpc }}-presentation-db"
    rds_openregister_instance_name: "{{ vpc }}-openregister-db"

  roles:
    - service_config

    - { role: s3_sync,
        when: sync,
        src: "{{ workdir }}/{{ vpc }}",
        dest: "s3://{{ s3_bucket_prefix }}.{{ vpc }}.{{ s3_bucket_suffix }}"
      }
