---
- stat: path="group_vars/tag_Environment_{{ vpc }}"
  register: overrides

- include_vars: "group_vars/tag_Environment_{{ vpc }}"
  when: overrides.stat.exists

- name: Create config directories
  file: name="{{ item }}" state=directory mode=0700
  with_items:
    - "{{ workdir }}"
    - "{{ workdir }}/{{ vpc }}"

- name: Create config register directories
  file: name="{{ workdir }}/{{ vpc }}/{{ item.key }}/openregister" state=directory mode=0700
  with_dict: "{{ register_groups }}"

- name: Generate openregister-java configuration files
  template:
    src="templates/openregister-config.yaml.j2"
    dest="{{ workdir }}/{{ vpc }}/{{ item.key }}/openregister/config.yaml"
  with_dict: "{{ register_groups }}"
